# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0002_auto_20160731_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 31, 9, 18, 50, 709063, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(default='owner', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='title', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 31, 9, 19, 7, 228561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
