# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import visual_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0003_auto_20160731_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=visual_art.models.thumbnail_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to=visual_art.models.original_path),
        ),
    ]
