# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import visual_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0004_auto_20160731_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(default=None, upload_to=visual_art.models.user_large_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='medium',
            field=models.ImageField(default=None, upload_to=visual_art.models.user_medium_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='small',
            field=models.ImageField(default=None, upload_to=visual_art.models.user_small_path),
            preserve_default=False,
        ),
    ]
