# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import visual_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0005_auto_20160804_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(null=True, upload_to=visual_art.models.user_large_path),
        ),
    ]
