# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0007_auto_20160804_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
