# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import visual_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0008_auto_20160805_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='huge',
            field=models.ImageField(null=True, upload_to=visual_art.models.user_huge_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
