# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0009_auto_20160806_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
