# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visual_art', '0010_image_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='favorite',
        ),
        migrations.AddField(
            model_name='image',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
