# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visual_art', '0012_image_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='favorite',
            field=models.ManyToManyField(related_name='image_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ManyToManyField(related_name='image_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
