# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 04:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0014_auto_20160807_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='md5',
            field=models.CharField(default='fsdaf', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
