# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0015_auto_20160808_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='favorite_count',
        ),
    ]
