# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0016_remove_image_favorite_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='visual_art.Tag'),
        ),
    ]
