# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_art', '0017_auto_20160808_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
