# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 14:19
from __future__ import unicode_literals

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to=audio.models.user_directory_path)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('owner', models.CharField(max_length=128)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
